"""initial schema

Revision ID: 0001
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("full_name", sa.String(120), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(30), nullable=False, server_default="teacher"), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("schools", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("academic_year", sa.String(32), nullable=False), sa.Column("default_language", sa.String(12), nullable=False, server_default="en"))
    op.create_table("classes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("school_id", sa.Integer(), sa.ForeignKey("schools.id"), nullable=False), sa.Column("name", sa.String(80), nullable=False), sa.Column("grade_level", sa.String(40), nullable=False))
    op.create_table("students", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("class_id", sa.Integer(), sa.ForeignKey("classes.id"), nullable=False), sa.Column("student_code", sa.String(40), nullable=False), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="active"))
    op.create_table("subjects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("school_id", sa.Integer(), sa.ForeignKey("schools.id"), nullable=False), sa.Column("name", sa.String(120), nullable=False))
    op.create_table("assessment_types", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("school_id", sa.Integer(), sa.ForeignKey("schools.id"), nullable=False), sa.Column("name", sa.String(100), nullable=False), sa.Column("max_score", sa.Float(), nullable=False), sa.Column("weight", sa.Float(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"))
    op.create_table("assessments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("assessment_type_id", sa.Integer(), sa.ForeignKey("assessment_types.id"), nullable=False), sa.Column("subject_id", sa.Integer(), sa.ForeignKey("subjects.id"), nullable=False), sa.Column("title", sa.String(180), nullable=False), sa.Column("date", sa.Date(), nullable=False))
    op.create_table("student_scores", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("student_id", sa.Integer(), sa.ForeignKey("students.id"), nullable=False), sa.Column("assessment_id", sa.Integer(), sa.ForeignKey("assessments.id"), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="entered"), sa.Column("score", sa.Float(), nullable=True), sa.Column("teacher_note", sa.String(500), nullable=True), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("student_id", "assessment_id", name="uq_student_assessment"))
    op.create_table("attendance", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("student_id", sa.Integer(), sa.ForeignKey("students.id"), nullable=False), sa.Column("date", sa.Date(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("student_id", "date", name="uq_student_attendance"))
    op.create_table("exams", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("class_id", sa.Integer(), sa.ForeignKey("classes.id"), nullable=False), sa.Column("subject_id", sa.Integer(), sa.ForeignKey("subjects.id"), nullable=False), sa.Column("title", sa.String(180), nullable=False), sa.Column("total_marks", sa.Float(), nullable=False), sa.Column("answer_key", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("questions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("exam_id", sa.Integer(), sa.ForeignKey("exams.id"), nullable=False), sa.Column("question_no", sa.Integer(), nullable=False), sa.Column("question_text", sa.Text(), nullable=False), sa.Column("max_score", sa.Float(), nullable=False), sa.Column("topic", sa.String(140), nullable=True), sa.Column("answer_type", sa.String(40), nullable=False, server_default="short_answer"))
    op.create_table("submissions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("exam_id", sa.Integer(), sa.ForeignKey("exams.id"), nullable=False), sa.Column("student_id", sa.Integer(), sa.ForeignKey("students.id"), nullable=False), sa.Column("original_filename", sa.String(255), nullable=False), sa.Column("stored_path", sa.String(500), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="uploaded"), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("ai_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("submission_id", sa.Integer(), sa.ForeignKey("submissions.id"), nullable=False), sa.Column("question_id", sa.Integer(), sa.ForeignKey("questions.id"), nullable=True), sa.Column("suggested_score", sa.Float(), nullable=True), sa.Column("confidence", sa.Float(), nullable=True), sa.Column("reason", sa.Text(), nullable=True), sa.Column("mistake_type", sa.String(120), nullable=True), sa.Column("topic", sa.String(140), nullable=True), sa.Column("feedback", sa.Text(), nullable=True), sa.Column("needs_teacher_review", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("teacher_score", sa.Float(), nullable=True), sa.Column("review_status", sa.String(30), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("mistakes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("student_id", sa.Integer(), sa.ForeignKey("students.id"), nullable=False), sa.Column("topic", sa.String(140), nullable=False), sa.Column("mistake_type", sa.String(140), nullable=False), sa.Column("occurrence_count", sa.Integer(), nullable=False, server_default="1"), sa.Column("last_seen", sa.Date(), nullable=False))
    op.create_table("teacher_comments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("student_id", sa.Integer(), sa.ForeignKey("students.id"), nullable=False), sa.Column("comment", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("entity", sa.String(80), nullable=False), sa.Column("entity_id", sa.Integer(), nullable=True), sa.Column("action", sa.String(80), nullable=False), sa.Column("old_value", sa.Text(), nullable=True), sa.Column("new_value", sa.Text(), nullable=True), sa.Column("reason", sa.String(500), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))

def downgrade():
    for t in ["audit_logs","teacher_comments","mistakes","ai_results","submissions","questions","exams","attendance","student_scores","assessments","assessment_types","subjects","students","classes","schools","users"]:
        op.drop_table(t)
